FROM consol/debian-xfce-vnc:v2.0.2

USER root

# + Установка OSCRIPT
ARG ONESCRIPT_VERSION="1.8.3"
ARG ONESCRIPT_PACKAGES="add 1connector cmdline messenger v8metadata-reader v8storage v8unpack vanessa-runner"

COPY ./src/onec/scripts/install-onescript.sh /tmp/install-onescript.sh
RUN \
    chmod +x /tmp/install-onescript.sh \
    && /tmp/install-onescript.sh $ONESCRIPT_VERSION $ONESCRIPT_PACKAGES
# - Установка OSCRIPT

